In [84]:
import pandas as pd

info = {
    "Name":["ram","kam","pal"],
    "CGPA":[9.15,9.16,9.80]
}
df = pd.DataFrame(info)
print(df)

  Name  CGPA
0  ram  9.15
1  kam  9.16
2  pal  9.80

In [85]:
df

  Name  CGPA
0  ram  9.15
1  kam  9.16
2  pal  9.80

In [86]:
s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [87]:
s = pd.Series([24,26,27,29], index=["raj","rajpal","pravin","getta"])
print(s)

print(s["raj"])
print(s["getta"])

# print(s[0])

raj       24
rajpal    26
pravin    27
getta     29
dtype: int64
24
29

In [88]:
info1 = {
    "Name":["raj","ramesh","gan"],
    "age":[20,22,21],
    "gpa":[9.4,9.3,9.9]
}
df = pd.DataFrame(info1)
print(df,type(df))

print(df.index)
print(df.columns)

     Name  age  gpa
0     raj   20  9.4
1  ramesh   22  9.3
2     gan   21  9.9 <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'age', 'gpa'], dtype='str')

In [89]:
df = pd.DataFrame([["ram",28],["raj",23],["pal",24]],columns=["Name","Age"])
print(df)

  Name  Age
0  ram   28
1  raj   23
2  pal   24

In [90]:
import numpy as np
np_arr = np.array([[1,2,3],[1,2,3]])
df = pd.DataFrame(np_arr,columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  1  2  3

In [91]:
import pandas as pd

df = pd.read_csv("17. employee_data.csv")

print(df,type(df))

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0 <class 'pandas.DataFrame'>

In [92]:
import pandas as pd
df = pd.read_json("17. employee_data.json")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [93]:
# df.head()
# df.tail()
# df.info()
# df.sample()
# df.shape

# df.describe()

df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [94]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [95]:
import pandas as pd
df = pd.read_csv("globalAirQuality.csv")
# print(df)
# df.describe()
df["city"]

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str

In [96]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [97]:
# df.loc[2]
# df.loc[0:2]

# df.iloc[0:3]
# df.loc[0,"aqi"]
# df.loc[0,["city","aqi"]]
# df.loc[0:2,["city","aqi"]]

# df.iloc[0:2,[2,11]]

# df.loc[0:2,["country","city","latitude","longitude"]]
# df.iloc[0:2,1:5]

# df.at[0,"city"]
# df.iat[0,2]

cities = df["city"]   #.copy()
cities[0] = "Delhi"

In [100]:
# df[df["aqi"] > 100]
df[(df["aqi"] > 100) & (df["temperature"] > 30)]
df[df["aqi"] > 100][["city","temperature"]]

aqi_data = df[(df["aqi"] > 100) & (df["temperature"] > 30) ][["city","temperature"]]
aqi_data
# aqi_data.iloc[0]
# aqi_data.loc[0] this give error not allows
aqi_data.loc[6]

# queries
aqi_val = 100
df.query("aqi > 100 & temperature > 30")[["city","aqi"]]
aqi_data = df.query("aqi > @aqi_val & temperature > 30")[["city","aqi"]].copy()
aqi_data

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

Current Directory: D:\AI_ML\pandas
Files in Directory: ['.ipynb_checkpoints', '17. employee_data.csv', '17. employee_data.json', '17. raw_data.csv', 'archive', 'globalAirQuality.csv', 'pandas_tutorial.ipynb']

In [121]:

import os

print("Current Directory:", os.getcwd())
print("Files in Directory:", os.listdir())

df = pd.read_csv("17. raw_data.csv")
df.isnull()
df.isnull().sum()
df.dropna()
df.fillna(0)

age_mean = df["age"].mean()
df["age"].fillna(age_mean)

cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

df.ffill()
df.bfill()

Current Directory: D:\AI_ML\pandas
Files in Directory: ['.ipynb_checkpoints', '17. employee_data.csv', '17. employee_data.json', '17. raw_data.csv', 'archive', 'globalAirQuality.csv', 'pandas_tutorial.ipynb']

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [130]:
df.duplicated()
df["country"].duplicated()
df[["country","gender"]].duplicated()
df2 = df.copy()
df.drop_duplicates(inplace =True)

In [131]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [133]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])

aqi_data["timestamp"].dtype

dtype('<M8[us]')

In [134]:
date_str = pd.Series([pd.to_datetime("2026-12-3")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [146]:
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()
df["name"].str.split(" ")
df["name"].str.split("@")
df["country"].str.contains("US")
df["country"].str.contains("india",case="False")

0     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
Name: country, dtype: bool

In [152]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [194]:
df2 = df.copy()
df2["tax"]=df2["income"].apply(lambda x:"20%" if x >= 50000 else "10%")

gender_map = {"Male":"M","Female":"F","Unknown":"U"}
df2["gender"] = df2["gender"].map(gender_map)

df2 = df2.assign(new_income = df2["income"] * 1.1)

df2["country"] = df2["country"].replace("USA","United State")
df2

    id          name   age       country gender   income  tax  new_income
0    1      John Doe  29.0  United State      M  55000.0  20%     60500.0
1    1      John Doe  29.0  United State      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN        Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United State      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0         Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0         China      M  51000.0  20%     56100.0
6    6           NaN  45.0         India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0           NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN        Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United State    NaN  58000.0  20%     63800.0